/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export function Marker(props) {
  const { nodes, materials } = useGLTF('./models/marker.glb')
  const texture = useTexture("./models/images/test.jpg")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body1.geometry}
        material={
          new MeshStandardMaterial({
            color: props.color, // Make color punchier on hover
            roughness: 0,
            metalness: 2,
          })
        }
        
        position={props.position}
        rotation={[ -Math.PI/2, props.angle, 0]}
        scale={0.005}
      >

      </mesh>
    </group>
  )
}

useGLTF.preload('./models/marker.glb')